# Generated by Django 4.2.20 on 2025-05-06 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0003_plant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('fertilize', 'Fertilize'), ('prune', 'Prune'), ('repot', 'Repot'), ('other', 'Other')], max_length=20)),
                ('frequency', models.IntegerField(help_text='Days between tasks')),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='care_tasks',
            field=models.ManyToManyField(blank=True, related_name='plants', to='my_app.caretask'),
        ),
    ]
